FROM php:7.4-fpm

MAINTAINER Chenli "touch_789@163.com"

RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -y curl telnet git zlib1g-dev libzip-dev vim procps libwebp-dev libjpeg-dev libpng-dev libfreetype6-dev && \
    /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone && \
    docker-php-ext-install zip pdo pdo_mysql opcache mysqli && \
    docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && \
    docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install -j$(nproc) bcmath && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    composer config -g repo.packagist composer https://packagist.phpcomposer.com && \
    php -r "unlink('composer-setup.php');" && \
    pecl install redis swoole  && \      
    rm -rf /tmp/pear && \
    docker-php-ext-enable redis swoole  && \
    apt-get clean && rm -rf /var/cache/apt/*
    
WORKDIR /var/www

#EXPOSE 80
