#php 7.4+ nginx +redis 示例

version: '3'
# 加入已创建的docker-compose-network网络组
# docker network create docker-compose-network
networks:
  docker-compose-network:
    external: true

services:
  web:
    image: touch789/php:74-fpm
    container_name: web
    networks:
      - docker-compose-network
    volumes:
      - ./:/www
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8081:80
    networks:
      - docker-compose-network
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./:/www
  redis:
    image: redis
    container_name: redis 
    command: 
      redis-server
    networks:
      - docker-compose-network
